/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    yoneticiler: YoneticilerAuthOperations;
  };
  blocks: {};
  collections: {
    medyalar: Medyalar;
    urunler: Urunler;
    urun_kategorileri: UrunKategorileri;
    portfoy_projeleri: PortfoyProjeleri;
    kampanyalar: Kampanyalar;
    sayfalar: Sayfalar;
    blog_yazilari: BlogYazilari;
    yoneticiler: Yoneticiler;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    medyalar: MedyalarSelect<false> | MedyalarSelect<true>;
    urunler: UrunlerSelect<false> | UrunlerSelect<true>;
    urun_kategorileri: UrunKategorileriSelect<false> | UrunKategorileriSelect<true>;
    portfoy_projeleri: PortfoyProjeleriSelect<false> | PortfoyProjeleriSelect<true>;
    kampanyalar: KampanyalarSelect<false> | KampanyalarSelect<true>;
    sayfalar: SayfalarSelect<false> | SayfalarSelect<true>;
    blog_yazilari: BlogYazilariSelect<false> | BlogYazilariSelect<true>;
    yoneticiler: YoneticilerSelect<false> | YoneticilerSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site_ayarlari: SiteAyarlari;
    ust_bilgi: UstBilgi;
    alt_bilgi: AltBilgi;
    iletisim_bilgileri: IletisimBilgileri;
    ana_sayfa_icerigi: AnaSayfaIcerigi;
  };
  globalsSelect: {
    site_ayarlari: SiteAyarlariSelect<false> | SiteAyarlariSelect<true>;
    ust_bilgi: UstBilgiSelect<false> | UstBilgiSelect<true>;
    alt_bilgi: AltBilgiSelect<false> | AltBilgiSelect<true>;
    iletisim_bilgileri: IletisimBilgileriSelect<false> | IletisimBilgileriSelect<true>;
    ana_sayfa_icerigi: AnaSayfaIcerigiSelect<false> | AnaSayfaIcerigiSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Yoneticiler;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface YoneticilerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medyalar".
 */
export interface Medyalar {
  id: number;
  alt: string;
  kaynak?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    kucuk?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    buyuk?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "urunler".
 */
export interface Urunler {
  id: number;
  /**
   * İçeriğin ana başlığıdır. Kartlarda ve detay sayfasında görünür.
   */
  baslik: string;
  /**
   * URL içinde kullanılacak kısa isimdir. Türkçe karakter ve boşluk yerine kısa, anlaşılır bir yapı tercih edin.
   */
  slug: string;
  /**
   * Kartlarda, liste görünümünde veya üst açıklama alanlarında özet olarak kullanılır.
   */
  kisa_aciklama?: string | null;
  /**
   * Bu içerik için öne çıkan ana görseldir. Liste kartlarında ve detay sayfasında kullanılır.
   */
  kapak_gorseli?: (number | null) | Medyalar;
  /**
   * Ürünün hangi kategori altında listeleneceğini belirler.
   */
  kategori: number | UrunKategorileri;
  /**
   * Ürün detay sayfasında görünen zengin içerik alanıdır.
   */
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ürün detay sayfasında kapak görselinin altında gösterilecek ek görseller.
   */
  galeri?: (number | Medyalar)[] | null;
  /**
   * Tam fiyat göstermek istemiyorsanız başlangıç bedeli girebilirsiniz. Örnek: 1500
   */
  baslangic_fiyati?: number | null;
  /**
   * Açık olduğunda başlangıç fiyatı kartta ve detay sayfasında gösterilir.
   */
  fiyat_gosterilsin_mi?: boolean | null;
  /**
   * Kapalıysa ürün detayında teklif butonu veya formu gösterilmez.
   */
  teklif_formu_aktif_mi?: boolean | null;
  /**
   * Teklif formu gönderilirken konu alanına otomatik yazılacak başlık.
   */
  teklif_konusu?: string | null;
  /**
   * WhatsApp butonuna basıldığında mesaj kutusuna düşecek hazır metin.
   */
  whatsapp_mesaji?: string | null;
  /**
   * İçerik sitede görünsün istiyorsanız "Yayında" seçin. Taslak içerikler yalnızca yönetimde görünür.
   */
  durum: 'taslak' | 'yayinda';
  /**
   * İçeriğin görünmesini istediğiniz tarihi belirler. Boş bırakılırsa kaydedildiği an esas alınır.
   */
  yayin_tarihi?: string | null;
  /**
   * Liste sıralamasını elle kontrol etmek için kullanılır. Küçük sayı daha yukarıda görünür.
   */
  sira_no?: number | null;
  /**
   * Arama motorlarında görünecek başlık, açıklama ve paylaşım görselini bu bölümden yönetin.
   */
  seo?: {
    /**
     * Google sonuçlarında görünen başlık. 70 karakterin altında tutun.
     */
    seo_baslik?: string | null;
    /**
     * Google sonuçlarında başlığın altında görünen kısa açıklama. 160 karakteri geçmeyin.
     */
    seo_aciklama?: string | null;
    /**
     * Aynı içeriğin birden fazla URL’si varsa arama motorlarına tercih edilen adresi belirtir.
     */
    kanonik_url?: string | null;
    /**
     * Sayfa sosyal medyada paylaşıldığında görünecek kapak görseli.
     */
    open_graph_gorseli?: (number | null) | Medyalar;
    indekslensin_mi?: boolean | null;
    /**
     * İleri seviye yapılandırılmış veri alanı. Genellikle geliştirici desteğiyle kullanılır.
     */
    yapilandirilmis_veri?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Bu alan editöre hızlı bir hatırlatma sağlar. İçerik doğrulaması için teknik alanların da dolu olması gerekir.
   */
  seo_kontrol_notu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "urun_kategorileri".
 */
export interface UrunKategorileri {
  id: number;
  /**
   * İçeriğin ana başlığıdır. Kartlarda ve detay sayfasında görünür.
   */
  baslik: string;
  /**
   * URL içinde kullanılacak kısa isimdir. Türkçe karakter ve boşluk yerine kısa, anlaşılır bir yapı tercih edin.
   */
  slug: string;
  /**
   * Kartlarda, liste görünümünde veya üst açıklama alanlarında özet olarak kullanılır.
   */
  kisa_aciklama?: string | null;
  /**
   * Bu içerik için öne çıkan ana görseldir. Liste kartlarında ve detay sayfasında kullanılır.
   */
  kapak_gorseli?: (number | null) | Medyalar;
  one_cikan?: boolean | null;
  /**
   * İçerik sitede görünsün istiyorsanız "Yayında" seçin. Taslak içerikler yalnızca yönetimde görünür.
   */
  durum: 'taslak' | 'yayinda';
  /**
   * İçeriğin görünmesini istediğiniz tarihi belirler. Boş bırakılırsa kaydedildiği an esas alınır.
   */
  yayin_tarihi?: string | null;
  /**
   * Liste sıralamasını elle kontrol etmek için kullanılır. Küçük sayı daha yukarıda görünür.
   */
  sira_no?: number | null;
  /**
   * Arama motorlarında görünecek başlık, açıklama ve paylaşım görselini bu bölümden yönetin.
   */
  seo?: {
    /**
     * Google sonuçlarında görünen başlık. 70 karakterin altında tutun.
     */
    seo_baslik?: string | null;
    /**
     * Google sonuçlarında başlığın altında görünen kısa açıklama. 160 karakteri geçmeyin.
     */
    seo_aciklama?: string | null;
    /**
     * Aynı içeriğin birden fazla URL’si varsa arama motorlarına tercih edilen adresi belirtir.
     */
    kanonik_url?: string | null;
    /**
     * Sayfa sosyal medyada paylaşıldığında görünecek kapak görseli.
     */
    open_graph_gorseli?: (number | null) | Medyalar;
    indekslensin_mi?: boolean | null;
    /**
     * İleri seviye yapılandırılmış veri alanı. Genellikle geliştirici desteğiyle kullanılır.
     */
    yapilandirilmis_veri?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Bu alan editöre hızlı bir hatırlatma sağlar. İçerik doğrulaması için teknik alanların da dolu olması gerekir.
   */
  seo_kontrol_notu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfoy_projeleri".
 */
export interface PortfoyProjeleri {
  id: number;
  /**
   * İçeriğin ana başlığıdır. Kartlarda ve detay sayfasında görünür.
   */
  baslik: string;
  /**
   * URL içinde kullanılacak kısa isimdir. Türkçe karakter ve boşluk yerine kısa, anlaşılır bir yapı tercih edin.
   */
  slug: string;
  /**
   * Kartlarda, liste görünümünde veya üst açıklama alanlarında özet olarak kullanılır.
   */
  kisa_aciklama?: string | null;
  /**
   * Bu içerik için öne çıkan ana görseldir. Liste kartlarında ve detay sayfasında kullanılır.
   */
  kapak_gorseli?: (number | null) | Medyalar;
  musteri_adi?: string | null;
  galeri?: (number | Medyalar)[] | null;
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  referans_notu?: string | null;
  /**
   * İçerik sitede görünsün istiyorsanız "Yayında" seçin. Taslak içerikler yalnızca yönetimde görünür.
   */
  durum: 'taslak' | 'yayinda';
  /**
   * İçeriğin görünmesini istediğiniz tarihi belirler. Boş bırakılırsa kaydedildiği an esas alınır.
   */
  yayin_tarihi?: string | null;
  /**
   * Liste sıralamasını elle kontrol etmek için kullanılır. Küçük sayı daha yukarıda görünür.
   */
  sira_no?: number | null;
  /**
   * Arama motorlarında görünecek başlık, açıklama ve paylaşım görselini bu bölümden yönetin.
   */
  seo?: {
    /**
     * Google sonuçlarında görünen başlık. 70 karakterin altında tutun.
     */
    seo_baslik?: string | null;
    /**
     * Google sonuçlarında başlığın altında görünen kısa açıklama. 160 karakteri geçmeyin.
     */
    seo_aciklama?: string | null;
    /**
     * Aynı içeriğin birden fazla URL’si varsa arama motorlarına tercih edilen adresi belirtir.
     */
    kanonik_url?: string | null;
    /**
     * Sayfa sosyal medyada paylaşıldığında görünecek kapak görseli.
     */
    open_graph_gorseli?: (number | null) | Medyalar;
    indekslensin_mi?: boolean | null;
    /**
     * İleri seviye yapılandırılmış veri alanı. Genellikle geliştirici desteğiyle kullanılır.
     */
    yapilandirilmis_veri?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Bu alan editöre hızlı bir hatırlatma sağlar. İçerik doğrulaması için teknik alanların da dolu olması gerekir.
   */
  seo_kontrol_notu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kampanyalar".
 */
export interface Kampanyalar {
  id: number;
  /**
   * İçeriğin ana başlığıdır. Kartlarda ve detay sayfasında görünür.
   */
  baslik: string;
  /**
   * URL içinde kullanılacak kısa isimdir. Türkçe karakter ve boşluk yerine kısa, anlaşılır bir yapı tercih edin.
   */
  slug: string;
  /**
   * Kartlarda, liste görünümünde veya üst açıklama alanlarında özet olarak kullanılır.
   */
  kisa_aciklama?: string | null;
  /**
   * Bu içerik için öne çıkan ana görseldir. Liste kartlarında ve detay sayfasında kullanılır.
   */
  kapak_gorseli?: (number | null) | Medyalar;
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  baslangic_tarihi: string;
  bitis_tarihi: string;
  one_cikart?: boolean | null;
  sayac_goster?: boolean | null;
  /**
   * İçerik sitede görünsün istiyorsanız "Yayında" seçin. Taslak içerikler yalnızca yönetimde görünür.
   */
  durum: 'taslak' | 'yayinda';
  /**
   * İçeriğin görünmesini istediğiniz tarihi belirler. Boş bırakılırsa kaydedildiği an esas alınır.
   */
  yayin_tarihi?: string | null;
  /**
   * Liste sıralamasını elle kontrol etmek için kullanılır. Küçük sayı daha yukarıda görünür.
   */
  sira_no?: number | null;
  /**
   * Arama motorlarında görünecek başlık, açıklama ve paylaşım görselini bu bölümden yönetin.
   */
  seo?: {
    /**
     * Google sonuçlarında görünen başlık. 70 karakterin altında tutun.
     */
    seo_baslik?: string | null;
    /**
     * Google sonuçlarında başlığın altında görünen kısa açıklama. 160 karakteri geçmeyin.
     */
    seo_aciklama?: string | null;
    /**
     * Aynı içeriğin birden fazla URL’si varsa arama motorlarına tercih edilen adresi belirtir.
     */
    kanonik_url?: string | null;
    /**
     * Sayfa sosyal medyada paylaşıldığında görünecek kapak görseli.
     */
    open_graph_gorseli?: (number | null) | Medyalar;
    indekslensin_mi?: boolean | null;
    /**
     * İleri seviye yapılandırılmış veri alanı. Genellikle geliştirici desteğiyle kullanılır.
     */
    yapilandirilmis_veri?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Bu alan editöre hızlı bir hatırlatma sağlar. İçerik doğrulaması için teknik alanların da dolu olması gerekir.
   */
  seo_kontrol_notu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sayfalar".
 */
export interface Sayfalar {
  id: number;
  /**
   * İçeriğin ana başlığıdır. Kartlarda ve detay sayfasında görünür.
   */
  baslik: string;
  /**
   * URL içinde kullanılacak kısa isimdir. Türkçe karakter ve boşluk yerine kısa, anlaşılır bir yapı tercih edin.
   */
  slug: string;
  /**
   * Kartlarda, liste görünümünde veya üst açıklama alanlarında özet olarak kullanılır.
   */
  kisa_aciklama?: string | null;
  /**
   * Bu içerik için öne çıkan ana görseldir. Liste kartlarında ve detay sayfasında kullanılır.
   */
  kapak_gorseli?: (number | null) | Medyalar;
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * İçerik sitede görünsün istiyorsanız "Yayında" seçin. Taslak içerikler yalnızca yönetimde görünür.
   */
  durum: 'taslak' | 'yayinda';
  /**
   * İçeriğin görünmesini istediğiniz tarihi belirler. Boş bırakılırsa kaydedildiği an esas alınır.
   */
  yayin_tarihi?: string | null;
  /**
   * Liste sıralamasını elle kontrol etmek için kullanılır. Küçük sayı daha yukarıda görünür.
   */
  sira_no?: number | null;
  /**
   * Arama motorlarında görünecek başlık, açıklama ve paylaşım görselini bu bölümden yönetin.
   */
  seo?: {
    /**
     * Google sonuçlarında görünen başlık. 70 karakterin altında tutun.
     */
    seo_baslik?: string | null;
    /**
     * Google sonuçlarında başlığın altında görünen kısa açıklama. 160 karakteri geçmeyin.
     */
    seo_aciklama?: string | null;
    /**
     * Aynı içeriğin birden fazla URL’si varsa arama motorlarına tercih edilen adresi belirtir.
     */
    kanonik_url?: string | null;
    /**
     * Sayfa sosyal medyada paylaşıldığında görünecek kapak görseli.
     */
    open_graph_gorseli?: (number | null) | Medyalar;
    indekslensin_mi?: boolean | null;
    /**
     * İleri seviye yapılandırılmış veri alanı. Genellikle geliştirici desteğiyle kullanılır.
     */
    yapilandirilmis_veri?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Bu alan editöre hızlı bir hatırlatma sağlar. İçerik doğrulaması için teknik alanların da dolu olması gerekir.
   */
  seo_kontrol_notu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_yazilari".
 */
export interface BlogYazilari {
  id: number;
  /**
   * İçeriğin ana başlığıdır. Kartlarda ve detay sayfasında görünür.
   */
  baslik: string;
  /**
   * URL içinde kullanılacak kısa isimdir. Türkçe karakter ve boşluk yerine kısa, anlaşılır bir yapı tercih edin.
   */
  slug: string;
  /**
   * Kartlarda, liste görünümünde veya üst açıklama alanlarında özet olarak kullanılır.
   */
  kisa_aciklama?: string | null;
  /**
   * Bu içerik için öne çıkan ana görseldir. Liste kartlarında ve detay sayfasında kullanılır.
   */
  kapak_gorseli?: (number | null) | Medyalar;
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  etiketler?: string[] | null;
  /**
   * İçerik sitede görünsün istiyorsanız "Yayında" seçin. Taslak içerikler yalnızca yönetimde görünür.
   */
  durum: 'taslak' | 'yayinda';
  /**
   * İçeriğin görünmesini istediğiniz tarihi belirler. Boş bırakılırsa kaydedildiği an esas alınır.
   */
  yayin_tarihi?: string | null;
  /**
   * Liste sıralamasını elle kontrol etmek için kullanılır. Küçük sayı daha yukarıda görünür.
   */
  sira_no?: number | null;
  /**
   * Arama motorlarında görünecek başlık, açıklama ve paylaşım görselini bu bölümden yönetin.
   */
  seo?: {
    /**
     * Google sonuçlarında görünen başlık. 70 karakterin altında tutun.
     */
    seo_baslik?: string | null;
    /**
     * Google sonuçlarında başlığın altında görünen kısa açıklama. 160 karakteri geçmeyin.
     */
    seo_aciklama?: string | null;
    /**
     * Aynı içeriğin birden fazla URL’si varsa arama motorlarına tercih edilen adresi belirtir.
     */
    kanonik_url?: string | null;
    /**
     * Sayfa sosyal medyada paylaşıldığında görünecek kapak görseli.
     */
    open_graph_gorseli?: (number | null) | Medyalar;
    indekslensin_mi?: boolean | null;
    /**
     * İleri seviye yapılandırılmış veri alanı. Genellikle geliştirici desteğiyle kullanılır.
     */
    yapilandirilmis_veri?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Bu alan editöre hızlı bir hatırlatma sağlar. İçerik doğrulaması için teknik alanların da dolu olması gerekir.
   */
  seo_kontrol_notu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yoneticiler".
 */
export interface Yoneticiler {
  id: number;
  /**
   * Yönetici listesinde ve hesap ekranında görünen ad soyad bilgisidir.
   */
  ad: string;
  /**
   * Süper Admin tüm yönetici işlemlerini yapabilir. Editör içerik yönetebilir ancak yönetici hesaplarını değiştiremez.
   */
  rol: 'super_admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'yoneticiler';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'medyalar';
        value: number | Medyalar;
      } | null)
    | ({
        relationTo: 'urunler';
        value: number | Urunler;
      } | null)
    | ({
        relationTo: 'urun_kategorileri';
        value: number | UrunKategorileri;
      } | null)
    | ({
        relationTo: 'portfoy_projeleri';
        value: number | PortfoyProjeleri;
      } | null)
    | ({
        relationTo: 'kampanyalar';
        value: number | Kampanyalar;
      } | null)
    | ({
        relationTo: 'sayfalar';
        value: number | Sayfalar;
      } | null)
    | ({
        relationTo: 'blog_yazilari';
        value: number | BlogYazilari;
      } | null)
    | ({
        relationTo: 'yoneticiler';
        value: number | Yoneticiler;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'yoneticiler';
    value: number | Yoneticiler;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'yoneticiler';
    value: number | Yoneticiler;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medyalar_select".
 */
export interface MedyalarSelect<T extends boolean = true> {
  alt?: T;
  kaynak?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        kucuk?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        buyuk?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "urunler_select".
 */
export interface UrunlerSelect<T extends boolean = true> {
  baslik?: T;
  slug?: T;
  kisa_aciklama?: T;
  kapak_gorseli?: T;
  kategori?: T;
  icerik?: T;
  galeri?: T;
  baslangic_fiyati?: T;
  fiyat_gosterilsin_mi?: T;
  teklif_formu_aktif_mi?: T;
  teklif_konusu?: T;
  whatsapp_mesaji?: T;
  durum?: T;
  yayin_tarihi?: T;
  sira_no?: T;
  seo?:
    | T
    | {
        seo_baslik?: T;
        seo_aciklama?: T;
        kanonik_url?: T;
        open_graph_gorseli?: T;
        indekslensin_mi?: T;
        yapilandirilmis_veri?: T;
      };
  seo_kontrol_notu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "urun_kategorileri_select".
 */
export interface UrunKategorileriSelect<T extends boolean = true> {
  baslik?: T;
  slug?: T;
  kisa_aciklama?: T;
  kapak_gorseli?: T;
  one_cikan?: T;
  durum?: T;
  yayin_tarihi?: T;
  sira_no?: T;
  seo?:
    | T
    | {
        seo_baslik?: T;
        seo_aciklama?: T;
        kanonik_url?: T;
        open_graph_gorseli?: T;
        indekslensin_mi?: T;
        yapilandirilmis_veri?: T;
      };
  seo_kontrol_notu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfoy_projeleri_select".
 */
export interface PortfoyProjeleriSelect<T extends boolean = true> {
  baslik?: T;
  slug?: T;
  kisa_aciklama?: T;
  kapak_gorseli?: T;
  musteri_adi?: T;
  galeri?: T;
  icerik?: T;
  referans_notu?: T;
  durum?: T;
  yayin_tarihi?: T;
  sira_no?: T;
  seo?:
    | T
    | {
        seo_baslik?: T;
        seo_aciklama?: T;
        kanonik_url?: T;
        open_graph_gorseli?: T;
        indekslensin_mi?: T;
        yapilandirilmis_veri?: T;
      };
  seo_kontrol_notu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kampanyalar_select".
 */
export interface KampanyalarSelect<T extends boolean = true> {
  baslik?: T;
  slug?: T;
  kisa_aciklama?: T;
  kapak_gorseli?: T;
  icerik?: T;
  baslangic_tarihi?: T;
  bitis_tarihi?: T;
  one_cikart?: T;
  sayac_goster?: T;
  durum?: T;
  yayin_tarihi?: T;
  sira_no?: T;
  seo?:
    | T
    | {
        seo_baslik?: T;
        seo_aciklama?: T;
        kanonik_url?: T;
        open_graph_gorseli?: T;
        indekslensin_mi?: T;
        yapilandirilmis_veri?: T;
      };
  seo_kontrol_notu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sayfalar_select".
 */
export interface SayfalarSelect<T extends boolean = true> {
  baslik?: T;
  slug?: T;
  kisa_aciklama?: T;
  kapak_gorseli?: T;
  icerik?: T;
  durum?: T;
  yayin_tarihi?: T;
  sira_no?: T;
  seo?:
    | T
    | {
        seo_baslik?: T;
        seo_aciklama?: T;
        kanonik_url?: T;
        open_graph_gorseli?: T;
        indekslensin_mi?: T;
        yapilandirilmis_veri?: T;
      };
  seo_kontrol_notu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_yazilari_select".
 */
export interface BlogYazilariSelect<T extends boolean = true> {
  baslik?: T;
  slug?: T;
  kisa_aciklama?: T;
  kapak_gorseli?: T;
  icerik?: T;
  etiketler?: T;
  durum?: T;
  yayin_tarihi?: T;
  sira_no?: T;
  seo?:
    | T
    | {
        seo_baslik?: T;
        seo_aciklama?: T;
        kanonik_url?: T;
        open_graph_gorseli?: T;
        indekslensin_mi?: T;
        yapilandirilmis_veri?: T;
      };
  seo_kontrol_notu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yoneticiler_select".
 */
export interface YoneticilerSelect<T extends boolean = true> {
  ad?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Sitenin genel firma bilgileri ve SEO kimliği bu bölümden yönetilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_ayarlari".
 */
export interface SiteAyarlari {
  id: number;
  /**
   * Header, footer ve tarayıcı başlığında kullanılacak marka adı.
   */
  firma_adi: string;
  /**
   * Ana sayfa ve meta açıklama alanlarında kullanılabilecek kısa firma özeti.
   */
  aciklama: string;
  /**
   * Üst bilgi, iletişim alanları ve teklif formlarında referans için kullanılır.
   */
  telefon?: string | null;
  /**
   * İletişim ve bildirim alanlarında kullanılacak ana kurumsal e-posta adresi.
   */
  eposta?: string | null;
  /**
   * Footer ve iletişim sayfasında gösterilecek açık adres bilgisi.
   */
  adres?: string | null;
  /**
   * Arama motorlarında görünecek başlık, açıklama ve paylaşım görselini bu bölümden yönetin.
   */
  seo?: {
    /**
     * Google sonuçlarında görünen başlık. 70 karakterin altında tutun.
     */
    seo_baslik?: string | null;
    /**
     * Google sonuçlarında başlığın altında görünen kısa açıklama. 160 karakteri geçmeyin.
     */
    seo_aciklama?: string | null;
    /**
     * Aynı içeriğin birden fazla URL’si varsa arama motorlarına tercih edilen adresi belirtir.
     */
    kanonik_url?: string | null;
    /**
     * Sayfa sosyal medyada paylaşıldığında görünecek kapak görseli.
     */
    open_graph_gorseli?: (number | null) | Medyalar;
    indekslensin_mi?: boolean | null;
    /**
     * İleri seviye yapılandırılmış veri alanı. Genellikle geliştirici desteğiyle kullanılır.
     */
    yapilandirilmis_veri?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sitenin üst menüsünde görünecek bağlantıları bu bölümden yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ust_bilgi".
 */
export interface UstBilgi {
  id: number;
  /**
   * Üst menü sıralaması buradaki listeye göre oluşur. Her satır bir menü bağlantısıdır.
   */
  menu_ogeleri?:
    | {
        /**
         * Menüde görünen kısa bağlantı adı.
         */
        etiket: string;
        /**
         * Örnek: /urunler, /portfoy veya https://... şeklinde bağlantı yazın.
         */
        baglanti: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer metni ve footer bağlantıları bu bölümden yönetilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alt_bilgi".
 */
export interface AltBilgi {
  id: number;
  /**
   * Footer içinde firmanızı özetleyen kısa açıklama veya telif metni.
   */
  metin?: string | null;
  /**
   * Footer içinde yan yana veya alt alta gösterilecek hızlı bağlantılar.
   */
  linkler?:
    | {
        /**
         * Footer bağlantısında görünen metin.
         */
        etiket: string;
        /**
         * Örnek: /iletisim, /kvkk veya harici bağlantı.
         */
        baglanti: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * İletişim sayfası ve footer iletişim alanı bu verilerle beslenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iletisim_bilgileri".
 */
export interface IletisimBilgileri {
  id: number;
  /**
   * Müşterilerin sizi arayacağı ana telefon numarası.
   */
  telefon?: string | null;
  /**
   * İletişim sayfasında ve teklif dönüşlerinde kullanılacak e-posta.
   */
  eposta?: string | null;
  /**
   * Harita yanında ya da iletişim kartında gösterilecek açık adres.
   */
  adres?: string | null;
  /**
   * Örnek: Hafta içi 09:00 - 18:00
   */
  calisma_saatleri?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Ana sayfadaki hero, bölüm başlıkları, süreç alanı ve teklif çağrısı bu ekrandan yönetilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ana_sayfa_icerigi".
 */
export interface AnaSayfaIcerigi {
  id: number;
  /**
   * Ana sayfanın ilk ekranında dönen hero slaytlarıdır. Tek kayıt varsa sabit görünür, birden fazla kayıt varsa kaydırmalı alan olur.
   */
  hero_kayitlari?:
    | {
        /**
         * Hero üstünde küçük vurgu etiketi olarak görünür. Örnek: Yeni sezon, UV Baskı, Hızlı Teslim.
         */
        etiket?: string | null;
        /**
         * Hero alanında büyük puntoda görünen ana başlık.
         */
        baslik?: string | null;
        /**
         * Başlığın altında görünen kısa açıklama metni.
         */
        metin?: string | null;
        /**
         * Hero arka planında veya sağ bölümünde gösterilecek ana görsel.
         */
        gorsel?: (number | null) | Medyalar;
        /**
         * Ana aksiyon butonunda görünen metin. Örnek: Teklif Al
         */
        birincil_buton_metin?: string | null;
        /**
         * Ana buton bağlantısı. Örnek: /iletisim, /urunler veya harici bir URL.
         */
        birincil_buton_link?: string | null;
        /**
         * İkinci butonda görünen yardımcı metin. Örnek: WhatsApp Yaz
         */
        ikincil_buton_metin?: string | null;
        /**
         * İkinci butonun yönleneceği bağlantı.
         */
        ikincil_buton_link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hero altında küçük özet sayılar olarak gösterilir. Örnek: 1200+ Proje, 24 Saat Hızlı Dönüş.
   */
  istatistikler?:
    | {
        /**
         * Örnek: 1200+, 18 Yıl, %98
         */
        deger?: string | null;
        /**
         * Değerin kısa açıklaması.
         */
        aciklama?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ana sayfadaki kategori bölümünün başlığı.
   */
  kategori_baslik?: string | null;
  /**
   * Kategori bölümünde başlığın altında görünen açıklama.
   */
  kategori_aciklama?: string | null;
  /**
   * Öne çıkan ürünler alanının başlığı.
   */
  urun_baslik?: string | null;
  /**
   * Ürünler bölümünde kullanılacak kısa tanıtım metni.
   */
  urun_aciklama?: string | null;
  /**
   * Portföy vitrininin başlığı.
   */
  portfoy_baslik?: string | null;
  /**
   * Portföy bölümünde başlığın altında gösterilecek açıklama.
   */
  portfoy_aciklama?: string | null;
  /**
   * Ana sayfadaki kampanya bölümünün başlığı.
   */
  kampanya_baslik?: string | null;
  /**
   * Kampanya alanında kullanılacak kısa açıklama.
   */
  kampanya_aciklama?: string | null;
  /**
   * Blog veya rehber içerik alanı başlığı.
   */
  blog_baslik?: string | null;
  /**
   * Blog kartlarının üstünde görünen kısa tanıtım metni.
   */
  blog_aciklama?: string | null;
  /**
   * Müşteriye nasıl çalıştığınızı anlatan adımlar. Ana sayfadaki süreç bölümünde görünür.
   */
  surec_adimlari?:
    | {
        /**
         * Örnek: Talep, Tasarım, Baskı, Teslimat
         */
        adim?: string | null;
        /**
         * Bu adımda neler yapıldığını anlatan kısa açıklama.
         */
        aciklama?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ana sayfanın teklif çağrısı bölümünün ana başlığı.
   */
  teklif_baslik?: string | null;
  /**
   * Teklif formunun üstünde kullanılacak yardımcı açıklama.
   */
  teklif_aciklama?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_ayarlari_select".
 */
export interface SiteAyarlariSelect<T extends boolean = true> {
  firma_adi?: T;
  aciklama?: T;
  telefon?: T;
  eposta?: T;
  adres?: T;
  seo?:
    | T
    | {
        seo_baslik?: T;
        seo_aciklama?: T;
        kanonik_url?: T;
        open_graph_gorseli?: T;
        indekslensin_mi?: T;
        yapilandirilmis_veri?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ust_bilgi_select".
 */
export interface UstBilgiSelect<T extends boolean = true> {
  menu_ogeleri?:
    | T
    | {
        etiket?: T;
        baglanti?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alt_bilgi_select".
 */
export interface AltBilgiSelect<T extends boolean = true> {
  metin?: T;
  linkler?:
    | T
    | {
        etiket?: T;
        baglanti?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iletisim_bilgileri_select".
 */
export interface IletisimBilgileriSelect<T extends boolean = true> {
  telefon?: T;
  eposta?: T;
  adres?: T;
  calisma_saatleri?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ana_sayfa_icerigi_select".
 */
export interface AnaSayfaIcerigiSelect<T extends boolean = true> {
  hero_kayitlari?:
    | T
    | {
        etiket?: T;
        baslik?: T;
        metin?: T;
        gorsel?: T;
        birincil_buton_metin?: T;
        birincil_buton_link?: T;
        ikincil_buton_metin?: T;
        ikincil_buton_link?: T;
        id?: T;
      };
  istatistikler?:
    | T
    | {
        deger?: T;
        aciklama?: T;
        id?: T;
      };
  kategori_baslik?: T;
  kategori_aciklama?: T;
  urun_baslik?: T;
  urun_aciklama?: T;
  portfoy_baslik?: T;
  portfoy_aciklama?: T;
  kampanya_baslik?: T;
  kampanya_aciklama?: T;
  blog_baslik?: T;
  blog_aciklama?: T;
  surec_adimlari?:
    | T
    | {
        adim?: T;
        aciklama?: T;
        id?: T;
      };
  teklif_baslik?: T;
  teklif_aciklama?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}